name: CreateRelease

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        qt: [5.13.2]
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      id: GetVersion
      run: |
        VT_VERSION=2.02
        echo ::set-output name=VERSION::${VT_VERSION}
    - name: Install Qt (Linux)
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt }}
        aqtversion: "==0.7.1"
    - name: CreateRelease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: darwinbeing/create-release@master
      with:
        tag_name: ${{ steps.GetVersion.outputs.VERSION }}
        release_name: Release ${{ steps.GetVersion.outputs.VERSION }}
        body: ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false


